[build]
publish = "dist"
command = "npm run build"
  [build.environment]
  TERM = "xterm"
  CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"

[[edge_functions]]
path = "/*"
function = "entry.netlify-edge"
[dev]
framework = "#static"
[[headers]]
  for = "/sw.js"
[headers.values]
  Cache-Control = "no-cache"
[[headers]]
  for = "/assets/images/*"
[headers.values]
  Cache-Control = "public, max-age=60"
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs.settings]
    preset = "desktop" # Optionally run Lighthouse using a desktop configuration

[[plugins]]
  # Run Cypress component tests during build
  package = "netlify-plugin-cypress@2.2.1"
  [plugins.inputs]
    record = false
  [plugins.inputs.postBuild]
    enable = true
